/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by '高德龙' at '17-8-5 上午9:28' with Gradle 2.14.1
 *
 * @author 高德龙, @date 17-8-5 上午9:28
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
